### ISSUE TITLE
Unable to launch the container app in the simulator for Macs with M1 processor

### ISSUE THREAD

**Issue by rafaellara** [FidelLimited/fidel-ios#8]
As part of your release notes in 1.8.2 I can see that is not possible to use the SDK in the ARM iOS simulator.
This limitation is still present in the latest 1.8.3.

I have tried to limit this by wrapping Fidel usage in a wrapper that prevents the code to be compiled for the specific target, only importing the Framework and using it with the following conditions

`#if !targetEnvironment(simulator) || (targetEnvironment(simulator) && !arch(arm64))`

Problem is that, with the settings added by the pod (`EXCLUDED_ARCHS[sdk=iphonesimulator*] = arm64`) the app does not run at all in these cases.

1. When do you plan to add this support?
2. Any workaround you're aware to fix this?

Thanks
Rafa

**Comment by ccorneliu** [comment]
Hello @rafaellara ! I'm looking for a solution to support ARM iOS Simulators. I am not aware of a workaround at the moment, but will let you know if I find any.

**Comment by ccorneliu** [comment]
Hey, @rafaellara , Please update to version `1.8.5`. We removed the excluded architectures build settings and compiled the framework to support simulators on your M1 machine.
