### ISSUE TITLE
Module compiled with Swift 5.3.1 cannot be imported by the Swift 5.4

### ISSUE THREAD

**Issue by alboiuvlad29** [FidelLimited/fidel-ios#9]
Hey there!
We've recently updated to the latest version of Xcode 12.5 and we're unable to import the Fidel module due to "Module compiled with Swift 5.3.1 cannot be imported by the Swift 5.4" error".
Could we please have the framework re-compiled using this version?

It may be worth enabling Library Evolution and adding this in the project.pbxproj:
`BUILD_LIBRARY_FOR_DISTRIBUTION = YES;`
Ref: https://swift.org/blog/library-evolution/

This way, we may not have to to wait for another re-compiled version later on.

Thanks in advance!

**Comment by cornelkar** [comment]
Thanks for your patience @alboiuvlad29 , we were already working on distributing a new version but had some issues. We transitioned to the XCFramework package now and enabled the `BUILD_LIBRARY_FOR_DISTRIBUTION`, of course. Please update to version `1.8.5`.

**Comment by ccorneliu** [comment]
Thanks for your patience @alboiuvlad29 , we were already working on distributing a new version but had some issues. We transitioned to the XCFramework package now and enabled the BUILD_LIBRARY_FOR_DISTRIBUTION, of course. Please update to version 1.8.5.
